# Copyright 2026 Federico Pannisco
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Drive the whole JSON -> SQL conversion.

Two passes over the dump:

1. observe every document to infer the schema;
2. re-read it and stream INSERT statements out.

Reading twice keeps memory flat: rows are buffered per table only up to
``batch_size`` before being flushed, so a 10 GB dump never has to fit in RAM.
"""

from __future__ import annotations

import datetime as _dt
from typing import Callable, Iterator

from . import __version__
from .infer import SchemaBuilder, Table
from .loader import iter_records
from .sql import (
    create_table,
    drop_table,
    foreign_keys,
    get_dialect,
    indexes,
    insert_statements,
    iter_rows,
)

BANNER = "-- " + "-" * 70


def _header(dialect_name: str, source: str, tables: list[Table]) -> str:
    now = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    total = sum(t.row_count for t in tables)
    lines = [
        BANNER,
        f"-- Generated by firestore-backup {__version__} on {now}",
        f"-- Source: {source}",
        f"-- Dialect: {dialect_name}",
        f"-- Tables: {len(tables)}   Rows: {total}",
        BANNER,
        "-- Firestore is schemaless: the types below were inferred from the data",
        "-- actually present in the dump. Review them before running this in",
        "-- production - a field that happened to be absent from every exported",
        "-- document cannot appear here.",
        BANNER,
        "",
    ]
    return "\n".join(lines)


def _schema_notes(tables: list[Table]) -> str:
    lines = ["-- Table map (Firestore collection -> SQL table)"]
    for table in tables:
        origin = "array field" if table.is_array_table else "collection"
        sample = sorted(table.source_paths)[:1]
        origin_path = sample[0] if sample else table.label
        plural = "row" if table.row_count == 1 else "rows"
        lines.append(
            f"--   {origin_path:<46} -> {table.sql_name}"
            f"   ({table.row_count} {plural}, {origin})"
        )
    lines.append("")
    return "\n".join(lines)


def generate_sql(
    dump_path: str,
    out_schema,
    out_data=None,
    *,
    dialect: str = "postgres",
    separator: str = "_",
    map_mode: str = "flatten",
    array_mode: str = "json",
    lowercase: bool = True,
    table_prefix: str = "",
    all_nullable: bool = False,
    batch_size: int = 200,
    drop: bool = False,
    transaction: bool = True,
    add_foreign_keys: bool = True,
    on_conflict: bool = False,
    fmt: str | None = None,
    on_progress: Callable[[str], None] | None = None,
) -> list[Table]:
    """Write DDL to *out_schema* and INSERTs to *out_data* (or the same file)."""
    engine = get_dialect(dialect)
    data_stream = out_data if out_data is not None else out_schema
    single_file = data_stream is out_schema

    def say(message: str) -> None:
        if on_progress:
            on_progress(message)

    # -- pass 1: infer ------------------------------------------------
    say("Pass 1/2 - inferring schema...")
    builder = SchemaBuilder(
        separator=separator,
        map_mode=map_mode,
        array_mode=array_mode,
        lowercase=lowercase,
        max_identifier=engine.identifier_limit,
        table_prefix=table_prefix,
        all_nullable=all_nullable,
    )
    seen = 0
    for record in iter_records(dump_path, fmt):
        builder.observe(record)
        seen += 1
        if seen % 5000 == 0:
            say(f"  {seen} documents inspected")
    tables = builder.finalize()
    say(f"  {seen} documents -> {len(tables)} tables")

    if not tables:
        out_schema.write("-- The dump contained no documents.\n")
        return tables

    # -- DDL -----------------------------------------------------------
    out_schema.write(_header(engine.name, dump_path, tables))
    out_schema.write(_schema_notes(tables))

    if transaction:
        out_schema.write(engine.begin() + "\n\n")

    if drop:
        out_schema.write("-- Existing tables are dropped first (--drop)\n")
        for table in reversed(tables):          # children before parents
            out_schema.write(drop_table(engine, table) + "\n")
        out_schema.write("\n")

    for table in tables:
        out_schema.write(create_table(engine, table) + "\n\n")

    for table in tables:
        for statement in indexes(engine, table):
            out_schema.write(statement + "\n")
    out_schema.write("\n")

    if transaction and not single_file:
        out_schema.write(engine.commit() + "\n")

    # -- pass 2: data --------------------------------------------------
    say("Pass 2/2 - writing rows...")
    if not single_file:
        data_stream.write(_header(engine.name, dump_path, tables))
        if transaction:
            data_stream.write(engine.begin() + "\n\n")
    else:
        data_stream.write("-- " + "=" * 68 + "\n-- DATA\n-- " + "=" * 68 + "\n\n")

    buffers: dict[object, list] = {}
    by_name: dict[object, Table] = {}
    written = 0

    def flush(table: Table) -> None:
        nonlocal written
        rows = buffers.get(table.key)
        if not rows:
            return
        for statement in insert_statements(
            engine, table, rows, batch_size=batch_size, on_conflict=on_conflict
        ):
            data_stream.write(statement + "\n")
        written += len(rows)
        buffers[table.key] = []

    for table, row in iter_rows(
        iter_records(dump_path, fmt), tables,
        separator=separator, map_mode=map_mode, array_mode=array_mode,
    ):
        by_name[table.key] = table
        buffers.setdefault(table.key, []).append(row)
        if len(buffers[table.key]) >= batch_size:
            flush(table)
            if written % 5000 < batch_size:
                say(f"  {written} rows written")

    for key, table in by_name.items():
        flush(table)

    data_stream.write("\n")

    # -- constraints ---------------------------------------------------
    if add_foreign_keys:
        constraints = foreign_keys(engine, tables)
        if constraints:
            data_stream.write(
                "-- Foreign keys are added last, on purpose: in Firestore a\n"
                "-- subcollection can live under a document that does not exist,\n"
                "-- so these may legitimately fail. Drop this block if they do.\n"
            )
            for statement in constraints:
                data_stream.write(statement + "\n")
            data_stream.write("\n")
        elif not get_dialect(dialect).supports_add_constraint:
            data_stream.write(
                "-- Foreign keys skipped: this engine cannot add them after the fact.\n\n"
            )

    if transaction:
        data_stream.write(engine.commit() + "\n")

    say(f"  {written} rows written")
    return tables


def describe(tables: list[Table]) -> Iterator[str]:
    """Human-readable schema summary for the ``inspect`` command."""
    for table in tables:
        plural = "row" if table.row_count == 1 else "rows"
        yield f"\n{table.sql_name}   ({table.row_count} {plural})"
        origin = sorted(table.source_paths)[:1]
        if origin:
            yield f"  from: {origin[0]}"
        for col in table.columns.values():
            flag = "" if table.nullable(col) else "  NOT NULL"
            marker = "*" if col.is_meta else " "
            yield f"  {marker} {col.sql_name:<38} {col.kind}{flag}"
